#Update all the sections by editing the data.yml file inside _data folder.

# Site Settings
title: Rodrigo Bressan
url: 'http://rodrigobressan.com'
# Style will be applied only after restarting the build or serve. Just choose one of the options.
theme_skin: turquoise # blue turquoise green berry orange ceramic

plugins:
  - jekyll-paginate

paginate: 4
paginate_path: "/blog/page:num/"

# Tracker
#analytics: UA-83979019-1

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style

# Build settings
encoding: "utf-8"
compress_html: # - http://jch.penibelst.de/
  clippings: all
  ignore:
    envs: development

# Development Settings
port: 5000
host: 0.0.0.0
safe: false

# Conversion
markdown:    kramdown
highlighter: rouge

# Markdown Processors
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge